project_id = "cfyhskxjvvqpnnzsebud"

[functions.create-operador]
verify_jwt = false

[functions.delete-operador]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.update-operador-email]
verify_jwt = false

[functions.create-empreendimento-user]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
