// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/listar-servicos.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
var BUILD_URL = "https://cfyhskxjvvqpnnzsebud.supabase.co";
var BUILD_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmeWhza3hqdnZxcG5uenNlYnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2MjU4MzAsImV4cCI6MjA4ODIwMTgzMH0.wKsMCD6ERmueGJwgVlaY5vEhEaWCSgU-wGIO7BEllL4";
function supabaseProjectUrl() {
  const url = BUILD_URL?.trim() || configuredEnv(["SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL n\xE3o configurada");
  return url;
}
function supabasePublishableKey() {
  if (BUILD_KEY?.trim()) return BUILD_KEY.trim();
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Chave public\xE1vel do Supabase n\xE3o configurada");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("Requisi\xE7\xE3o sem token OAuth verificado");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }]
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/listar-servicos.ts
var listar_servicos_default = defineTool({
  name: "listar_servicos",
  title: "Listar servi\xE7os",
  description: "Lista servi\xE7os da Nacional G\xE1s com filtros por UF, condom\xEDnio, apartamento, status, tipo, protocolo e per\xEDodo de agendamento.",
  inputSchema: {
    uf: z.string().trim().length(2).optional().describe("Sigla do estado, ex: CE ou BA"),
    condominio: z.string().trim().optional().describe("Parte do nome do condom\xEDnio"),
    apartamento: z.string().trim().optional(),
    bloco: z.string().trim().optional(),
    status: z.enum(["pendente", "agendado", "executado", "cancelado"]).optional().describe("Status do atendimento"),
    tipo_servico: z.string().trim().optional(),
    numero_protocolo: z.string().trim().optional(),
    data_inicio: z.string().trim().optional().describe("Data inicial do agendamento (YYYY-MM-DD)"),
    data_fim: z.string().trim().optional().describe("Data final do agendamento (YYYY-MM-DD)"),
    limite: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de registros (padr\xE3o 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("servicos_nacional_gas").select(
      "id, numero_protocolo, data_solicitacao, uf, condominio_nome_original, bloco, apartamento, morador_nome, telefone, email, cpf_cnpj, tipo_servico, data_agendamento, turno, status_atendimento, tecnico_id, valor_servico, forma_pagamento, observacao"
    ).order("data_agendamento", { ascending: false, nullsFirst: false }).limit(input.limite ?? 50);
    if (input.uf) query = query.eq("uf", input.uf.toUpperCase());
    if (input.status) query = query.eq("status_atendimento", input.status);
    if (input.numero_protocolo) query = query.ilike("numero_protocolo", `%${input.numero_protocolo}%`);
    if (input.condominio) query = query.ilike("condominio_nome_original", `%${input.condominio}%`);
    if (input.apartamento) query = query.ilike("apartamento", `%${input.apartamento}%`);
    if (input.bloco) query = query.ilike("bloco", `%${input.bloco}%`);
    if (input.tipo_servico) query = query.ilike("tipo_servico", `%${input.tipo_servico}%`);
    if (input.data_inicio) query = query.gte("data_agendamento", input.data_inicio);
    if (input.data_fim) query = query.lte("data_agendamento", input.data_fim);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ total: data?.length ?? 0, servicos: data ?? [] });
  }
});

// src/lib/mcp/tools/buscar-servico.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var buscar_servico_default = defineTool2({
  name: "buscar_servico",
  title: "Buscar servi\xE7o",
  description: "Retorna os detalhes completos de um servi\xE7o pelo n\xFAmero de protocolo ou pelo ID.",
  inputSchema: {
    numero_protocolo: z2.string().trim().optional().describe("Ex: NG-000123"),
    id: z2.string().uuid().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ numero_protocolo, id }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("N\xE3o autenticado.");
    if (!numero_protocolo && !id) return errorResult("Informe numero_protocolo ou id.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("servicos_nacional_gas").select("*").limit(1);
    query = id ? query.eq("id", id) : query.eq("numero_protocolo", numero_protocolo);
    const { data, error } = await query.maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Servi\xE7o n\xE3o encontrado.");
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/listar-empreendimentos.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var listar_empreendimentos_default = defineTool3({
  name: "listar_empreendimentos",
  title: "Listar empreendimentos",
  description: "Lista os condom\xEDnios (empreendimentos terceirizados) com UF, rota e quantidade de medidores.",
  inputSchema: {
    uf: z3.string().trim().length(2).optional(),
    nome: z3.string().trim().optional().describe("Parte do nome do condom\xEDnio"),
    rota: z3.number().int().optional(),
    limite: z3.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("empreendimentos_terceirizados").select("id, nome, uf, endereco, rota, quantidade_medidores, latitude, longitude").order("nome").limit(input.limite ?? 200);
    if (input.uf) query = query.eq("uf", input.uf.toUpperCase());
    if (input.nome) query = query.ilike("nome", `%${input.nome}%`);
    if (input.rota !== void 0) query = query.eq("rota", input.rota);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ total: data?.length ?? 0, empreendimentos: data ?? [] });
  }
});

// src/lib/mcp/tools/listar-operadores.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var listar_operadores_default = defineTool4({
  name: "listar_operadores",
  title: "Listar operadores",
  description: "Lista os t\xE9cnicos/operadores cadastrados, com id, nome, e-mail e status.",
  inputSchema: {
    apenas_ativos: z4.boolean().optional().describe("Padr\xE3o: true")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ apenas_ativos = true }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("operadores").select("id, nome, email, status").order("nome");
    if (apenas_ativos) query = query.eq("status", "ativo");
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ total: data?.length ?? 0, operadores: data ?? [] });
  }
});

// src/lib/mcp/tools/resumo-operacional.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^3.25.76";
var resumo_operacional_default = defineTool5({
  name: "resumo_operacional",
  title: "Resumo operacional",
  description: "Retorna contagens de servi\xE7os por status e por tipo em um per\xEDodo de agendamento, opcionalmente filtrado por UF.",
  inputSchema: {
    uf: z5.string().trim().length(2).optional(),
    data_inicio: z5.string().trim().optional().describe("YYYY-MM-DD"),
    data_fim: z5.string().trim().optional().describe("YYYY-MM-DD")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("servicos_nacional_gas").select("status_atendimento, tipo_servico, valor_servico, uf, data_agendamento").limit(5e3);
    if (input.uf) query = query.eq("uf", input.uf.toUpperCase());
    if (input.data_inicio) query = query.gte("data_agendamento", input.data_inicio);
    if (input.data_fim) query = query.lte("data_agendamento", input.data_fim);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    const porStatus = {};
    const porTipo = {};
    let valorTotal = 0;
    for (const row of data ?? []) {
      porStatus[row.status_atendimento] = (porStatus[row.status_atendimento] ?? 0) + 1;
      porTipo[row.tipo_servico] = (porTipo[row.tipo_servico] ?? 0) + 1;
      if (typeof row.valor_servico === "number") valorTotal += row.valor_servico;
    }
    return jsonResult({
      total: data?.length ?? 0,
      por_status: porStatus,
      por_tipo: porTipo,
      valor_total: Number(valorTotal.toFixed(2))
    });
  }
});

// src/lib/mcp/tools/criar-servico.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z6 } from "npm:zod@^3.25.76";

// src/lib/duplicidadeServico.ts
var STATUS_ABERTO = ["pendente", "agendado"];
var normText = (v) => (v ?? "").toString().normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/\s+/g, " ");
var normCondo = (v) => {
  let s = normText(v);
  s = s.replace(/\([^)]*\)/g, " ");
  s = s.replace(/^ba\s+/, " ");
  s = s.replace(/\b(condominio|cond|residencial|resid|edificio|ed)\b/g, " ");
  s = s.replace(/[^a-z0-9]/g, "");
  return s;
};
var normUnidade = (v) => {
  let s = normText(v).replace(/[^a-z0-9]/g, "");
  if (s === "unico" || s === "u") s = "";
  s = s.replace(/^0+/, "");
  return s;
};
var makeServicoDupKey = (row) => [
  normText(row.uf),
  normCondo(row.condominio_nome_original),
  normUnidade(row.bloco),
  normUnidade(row.apartamento),
  normText(row.morador_nome).replace(/[^a-z0-9]/g, ""),
  normText(row.tipo_servico).replace(/[^a-z0-9]/g, "")
].join("|");
async function buscarServicoDuplicado(client, row) {
  const chave = makeServicoDupKey(row);
  let query = client.from("servicos_nacional_gas").select("id, numero_protocolo, status_atendimento, uf, condominio_nome_original, bloco, apartamento, morador_nome, tipo_servico").in("status_atendimento", STATUS_ABERTO).limit(1e3);
  if (row.uf) query = query.eq("uf", String(row.uf).toUpperCase());
  const { data, error } = await query;
  if (error) throw error;
  const achado = (data || []).find((s) => makeServicoDupKey(s) === chave);
  return achado ? { id: achado.id, numero_protocolo: achado.numero_protocolo, status_atendimento: achado.status_atendimento } : null;
}

// src/lib/mcp/tools/criar-servico.ts
var criar_servico_default = defineTool6({
  name: "criar_servico",
  title: "Criar servi\xE7o",
  description: "Cria um novo servi\xE7o da Nacional G\xE1s. O n\xFAmero de protocolo \xE9 gerado automaticamente. Informe UF e o nome do condom\xEDnio exatamente como cadastrado. Servi\xE7os duplicados (mesmo condom\xEDnio, unidade, morador e tipo, ainda em aberto) s\xE3o bloqueados salvo permitir_duplicado.",
  inputSchema: {
    uf: z6.string().trim().length(2).describe("CE ou BA"),
    condominio_nome: z6.string().trim().min(1).describe("Nome do condom\xEDnio"),
    tipo_servico: z6.string().trim().min(1).describe("Ex: Visita T\xE9cnica, Religa\xE7\xE3o, Desligamento"),
    bloco: z6.string().trim().optional(),
    apartamento: z6.string().trim().optional(),
    morador_nome: z6.string().trim().optional(),
    telefone: z6.string().trim().optional(),
    email: z6.string().trim().optional(),
    cpf_cnpj: z6.string().trim().optional(),
    fonte: z6.string().trim().optional(),
    data_solicitacao: z6.string().trim().optional().describe("YYYY-MM-DD"),
    data_agendamento: z6.string().trim().optional().describe("YYYY-MM-DD"),
    turno: z6.enum(["manha", "tarde"]).optional(),
    status_atendimento: z6.enum(["pendente", "agendado", "executado", "cancelado"]).optional(),
    valor_servico: z6.number().optional(),
    forma_pagamento: z6.string().trim().optional(),
    observacao: z6.string().trim().max(1e3).optional(),
    permitir_duplicado: z6.boolean().optional().describe("Cria mesmo que j\xE1 exista servi\xE7o igual em aberto")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("N\xE3o autenticado.");
    const supabase = supabaseForUser(ctx);
    const uf = input.uf.toUpperCase();
    if (!input.permitir_duplicado) {
      const dup = await buscarServicoDuplicado(supabase, {
        uf,
        condominio_nome_original: input.condominio_nome,
        bloco: input.bloco,
        apartamento: input.apartamento,
        morador_nome: input.morador_nome,
        tipo_servico: input.tipo_servico
      });
      if (dup) {
        return errorResult(
          `Servi\xE7o duplicado: j\xE1 existe um atendimento em aberto (protocolo ${dup.numero_protocolo ?? dup.id}, status ${dup.status_atendimento}) para essa unidade, morador e tipo de servi\xE7o. Use permitir_duplicado=true para for\xE7ar.`
        );
      }
    }
    const { data: emp } = await supabase.from("empreendimentos_terceirizados").select("id, nome").eq("uf", uf).ilike("nome", `%${input.condominio_nome}%`).limit(2);
    const empreendimento_id = emp && emp.length === 1 ? emp[0].id : null;
    const { data, error } = await supabase.from("servicos_nacional_gas").insert({
      uf,
      empreendimento_id,
      condominio_nome_original: input.condominio_nome,
      bloco: input.bloco ?? null,
      apartamento: input.apartamento ?? null,
      morador_nome: input.morador_nome ?? null,
      telefone: input.telefone ?? null,
      email: input.email ?? null,
      cpf_cnpj: input.cpf_cnpj ?? null,
      fonte: input.fonte ?? "MCP",
      tipo_servico: input.tipo_servico,
      data_solicitacao: input.data_solicitacao ?? null,
      data_agendamento: input.data_agendamento ?? null,
      turno: input.turno ?? null,
      status_atendimento: input.status_atendimento ?? (input.data_agendamento ? "agendado" : "pendente"),
      valor_servico: input.valor_servico ?? null,
      forma_pagamento: input.forma_pagamento ?? null,
      observacao: input.observacao ?? null
    }).select("id, numero_protocolo, condominio_nome_original, status_atendimento, data_agendamento").single();
    if (error) return errorResult(error.message);
    return jsonResult({
      criado: data,
      empreendimento_vinculado: empreendimento_id ? emp?.[0]?.nome : null,
      aviso: empreendimento_id ? void 0 : "Nenhum empreendimento \xFAnico encontrado com esse nome; o servi\xE7o ficou sem v\xEDnculo."
    });
  }
});

// src/lib/mcp/tools/atualizar-servico.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z7 } from "npm:zod@^3.25.76";
var atualizar_servico_default = defineTool7({
  name: "atualizar_servico",
  title: "Atualizar servi\xE7o",
  description: "Atualiza campos de um servi\xE7o existente (identificado por ID ou protocolo): agendamento, turno, status, t\xE9cnico, valor, forma de pagamento e observa\xE7\xE3o.",
  inputSchema: {
    id: z7.string().uuid().optional(),
    numero_protocolo: z7.string().trim().optional(),
    data_agendamento: z7.string().trim().optional().describe("YYYY-MM-DD"),
    turno: z7.enum(["manha", "tarde"]).optional(),
    status_atendimento: z7.enum(["pendente", "agendado", "executado", "cancelado"]).optional(),
    tecnico_id: z7.string().uuid().optional().describe("ID do operador (ver listar_operadores)"),
    morador_nome: z7.string().trim().optional(),
    telefone: z7.string().trim().optional(),
    email: z7.string().trim().optional(),
    cpf_cnpj: z7.string().trim().optional(),
    valor_servico: z7.number().optional(),
    forma_pagamento: z7.string().trim().optional(),
    observacao: z7.string().trim().max(1e3).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("N\xE3o autenticado.");
    const { id, numero_protocolo, ...campos } = input;
    if (!id && !numero_protocolo) return errorResult("Informe id ou numero_protocolo.");
    const updates = Object.fromEntries(
      Object.entries(campos).filter(([, v]) => v !== void 0)
    );
    if (Object.keys(updates).length === 0) return errorResult("Nenhum campo para atualizar.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("servicos_nacional_gas").update(updates);
    query = id ? query.eq("id", id) : query.eq("numero_protocolo", numero_protocolo);
    const { data, error } = await query.select(
      "id, numero_protocolo, condominio_nome_original, bloco, apartamento, status_atendimento, data_agendamento, turno, tecnico_id, valor_servico"
    );
    if (error) return errorResult(error.message);
    if (!data || data.length === 0) return errorResult("Servi\xE7o n\xE3o encontrado ou sem permiss\xE3o.");
    return jsonResult({ atualizados: data.length, servicos: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "cfyhskxjvvqpnnzsebud";
var mcp_default = defineMcp({
  name: "ag-ngd",
  title: "ag-ngd",
  version: "0.1.0",
  instructions: "Ferramentas do sistema de medi\xE7\xE3o e servi\xE7os da Nacional G\xE1s (UFs CE e BA). Use listar_servicos/buscar_servico para consultar atendimentos, listar_empreendimentos para condom\xEDnios, listar_operadores para t\xE9cnicos, resumo_operacional para contagens, criar_servico para abrir um novo atendimento e atualizar_servico para agendar, atribuir t\xE9cnico ou mudar status. Datas no formato YYYY-MM-DD.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    listar_servicos_default,
    buscar_servico_default,
    listar_empreendimentos_default,
    listar_operadores_default,
    resumo_operacional_default,
    criar_servico_default,
    atualizar_servico_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
